# -*-coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils import timezone
from django.db import models
class patient_data(models.Model):
    id=models.AutoField(primary_key=True)
    fname=models.CharField(max_length = 50,null=True,blank=True)
    phone_contact=models.CharField(max_length = 50,null=True,blank=True)
    lname=models.CharField(max_length = 50)
    DOB=models.DateField(auto_now=False)
    age=models.CharField(max_length = 50)
    sex=models.CharField(max_length = 50)
    allow_patient_portal=models.CharField(max_length = 30)
    flag=models.IntegerField()
    class Meta:
        db_table = 'patient_data'
    def __str__(self):
        return patient_data.object.all()
class meter_checker(models.Model):
    gender=models.CharField(max_length = 50)
    meter_type=models.CharField(max_length = 50)
    fever_status=models.CharField(max_length = 50)
    breath_status=models.CharField(max_length = 50)
    soreThroat_status=models.CharField(max_length = 50)
    nauseaVomit_status=models.CharField(max_length = 50)
    confusion_status=models.CharField(max_length = 50)
    cough_status=models.CharField(max_length = 50)
    chestpain_status=models.CharField(max_length = 50)
    cholestrol=models.CharField(max_length = 50)
    diarhoea_status=models.CharField(max_length = 50)
    heart_rate=models.CharField(max_length = 50)
    temperature=models.CharField(max_length = 50)
    respiration=models.CharField(max_length = 50)
    spo2=models.CharField(max_length = 50)
    systolic=models.CharField(max_length = 50)
    diastolic=models.CharField(max_length = 50)
    swelling=models.CharField(max_length = 50)
    leuckocyte=models.CharField(max_length = 50)
    protien=models.CharField(max_length = 50)
    nitrite=models.CharField(max_length = 50)
    ph=models.CharField(max_length = 50)
    hematuria_blood=models.CharField(max_length = 50)
    specific_gravity=models.CharField(max_length = 50)
    ketone=models.CharField(max_length = 50)
    glucose_urine=models.CharField(max_length = 50)
    glucose_blood=models.CharField(max_length = 50)
    ecg_status=models.CharField(max_length = 50)
    exerciseAngina_status=models.CharField(max_length = 50)
    STdepression_status=models.CharField(max_length = 50)
    slopePeak_status=models.CharField(max_length = 50)
    flouroscopy=models.CharField(max_length = 50)
    thal_status=models.CharField(max_length = 50)
    urobilinogen=models.CharField(max_length = 50)
    bilirubin=models.CharField(max_length = 50)
    creatinine=models.CharField(max_length = 50)
    igG=models.CharField(max_length = 50)
    igM=models.CharField(max_length = 50)
    pr=models.CharField(max_length = 50)
    qt=models.CharField(max_length = 50)
    qrs=models.CharField(max_length = 50)
    rr=models.CharField(max_length = 50)
    submit_date=models.DateTimeField()
    mid=models.IntegerField(primary_key=True)
    pid=models.IntegerField()
    age=models.IntegerField()
    fever_days=models.IntegerField()
    breath_days=models.IntegerField()
    headache_days=models.IntegerField()
    soreThroat_days=models.IntegerField()
    rhinorrhoea_days=models.IntegerField()
    nauseaVomit_days=models.IntegerField()
    muscleAche_days=models.IntegerField()
    molting_days=models.IntegerField()
    anyChronic_days=models.CharField(max_length = 50)
    class Meta:
        db_table = 'meter_checker'
class meter_result(models.Model):
    mid=models.IntegerField()
    id=models.IntegerField(primary_key=True)
    result= models.CharField(max_length = 50)
    description= models.CharField(max_length =150)
    result_date=models.DateTimeField()
    class Meta:
        db_table = 'meter_result'